"use client";

import { motion } from "framer-motion";
import Link from "next/link";

export default function Methodology() {
  return (
    <>
      <section className="bg-stark-white text-absolute-black pt-32 pb-24 px-6 lg:px-12 min-h-[60vh] flex flex-col justify-center">
        <div className="max-w-7xl mx-auto w-full">
          <motion.h1 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            className="font-sans text-[clamp(3rem,8vw,8rem)] font-bold tracking-tighter uppercase leading-[0.9] mb-12"
          >
            THE END OF <br/>
            THE BILLABLE HOUR.
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.2 }}
            className="font-serif text-3xl italic max-w-4xl leading-relaxed"
          >
            We believe that a professional&apos;s judgment is their most valuable asset, and that selling it by the hour is a fundamental misallocation of capital.
          </motion.p>
        </div>
      </section>

      <section className="bg-off-black py-32 px-6 lg:px-12 text-stark-white">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-0 border-t border-l border-white/20">
            {/* TENET 1 */}
            <div className="border-r border-b border-white/20 p-12 bg-absolute-black hover:bg-stark-white hover:text-absolute-black transition-colors duration-500 group">
              <span className="font-mono text-signal-orange text-8xl font-bold opacity-30 group-hover:opacity-10 transition-opacity">01</span>
              <h3 className="font-sans text-2xl font-bold uppercase mt-8 mb-6 tracking-widest">[ LEVERAGE OVER LABOR ]</h3>
              <p className="font-serif text-lg leading-relaxed">
                You cannot scale yourself. True wealth and impact are generated by building systems that operate independently of your time. We teach you how to build those systems.
              </p>
            </div>
            {/* TENET 2 */}
            <div className="border-r border-b border-white/20 p-12 bg-absolute-black hover:bg-stark-white hover:text-absolute-black transition-colors duration-500 group">
              <span className="font-mono text-signal-orange text-8xl font-bold opacity-30 group-hover:opacity-10 transition-opacity">02</span>
              <h3 className="font-sans text-2xl font-bold uppercase mt-8 mb-6 tracking-widest">[ NO-CODE AS ARCHITECTURE ]</h3>
              <p className="font-serif text-lg leading-relaxed">
                Software development is no longer constrained by syntax. The modern no-code stack allows domain experts to act as architects, assembling powerful digital assets without writing code.
              </p>
            </div>
            {/* TENET 3 */}
            <div className="border-r border-b border-white/20 p-12 bg-absolute-black hover:bg-stark-white hover:text-absolute-black transition-colors duration-500 group">
              <span className="font-mono text-signal-orange text-8xl font-bold opacity-30 group-hover:opacity-10 transition-opacity">03</span>
              <h3 className="font-sans text-2xl font-bold uppercase mt-8 mb-6 tracking-widest">[ DOMAIN EXPERTISE IS THE MOAT ]</h3>
              <p className="font-serif text-lg leading-relaxed">
                Anyone can learn a software tool. Very few people have ten years of hard-won experience in compliance, logistics, or commercial real estate. Your expertise is the competitive advantage; the software is just the delivery mechanism.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-stark-white text-absolute-black py-40 px-6 lg:px-12 text-center text-stark-white">
        <h2 className="font-sans text-5xl font-bold uppercase tracking-widest mb-12 text-absolute-black">READY TO BUILD?</h2>
        <Link href="/curriculum" className="inline-block bg-signal-orange text-stark-white font-sans font-bold uppercase tracking-widest px-12 py-6 hover:bg-orange-600 transition-colors cursor-pointer shadow-2xl">
          EXPLORE THE CURRICULUM
        </Link>
      </section>
    </>
  );
}
